const NAVIGATOR = {
  LOGIN_FLOW: 'LOGIN_FLOW',
  LANDING_FLOW: 'LANDING_FLOW',
};

const LOGIN_STACK = {
  LOGIN: 'LOGIN',
};

const LANDING_STACK = {
  LANDING: 'LANDING',
  INDIVIDUAL_CHARACTER: 'INDIVIDUAL_CHARACTER',
  LOCATION: 'LOCATION',
};

export default {
  NAVIGATOR,
  LOGIN_STACK,
  LANDING_STACK,
};
